# Form implementation generated from reading ui file 'E:\VideoWatcher\UI\dbViewForm.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.but_bili_up = QtWidgets.QPushButton(parent=Form)
        self.but_bili_up.setObjectName("but_bili_up")
        self.gridLayout_2.addWidget(self.but_bili_up, 0, 0, 1, 1)
        self.but_bili_video = QtWidgets.QPushButton(parent=Form)
        self.but_bili_video.setObjectName("but_bili_video")
        self.gridLayout_2.addWidget(self.but_bili_video, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.but_lastpage = QtWidgets.QPushButton(parent=Form)
        self.but_lastpage.setMaximumSize(QtCore.QSize(23, 23))
        self.but_lastpage.setObjectName("but_lastpage")
        self.gridLayout.addWidget(self.but_lastpage, 0, 0, 1, 1)
        self.but_nextpage = QtWidgets.QPushButton(parent=Form)
        self.but_nextpage.setMaximumSize(QtCore.QSize(23, 23))
        self.but_nextpage.setObjectName("but_nextpage")
        self.gridLayout.addWidget(self.but_nextpage, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(parent=Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 378, 170))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 4)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.but_bili_up_exc = QtWidgets.QPushButton(parent=Form)
        self.but_bili_up_exc.setObjectName("but_bili_up_exc")
        self.gridLayout_2.addWidget(self.but_bili_up_exc, 0, 3, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(parent=Form)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_2.addWidget(self.toolButton_2, 1, 1, 1, 1)
        self.toolButton = QtWidgets.QToolButton(parent=Form)
        self.toolButton.setToolTip("")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 1, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(parent=Form)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_2.addWidget(self.toolButton_3, 1, 3, 1, 1)

        self.retranslateUi(Form)
        self.but_bili_up.clicked.connect(Form.on_click_bili_up) # type: ignore
        self.but_bili_video.clicked.connect(Form.on_click_bili_taged_video) # type: ignore
        self.but_bili_up_exc.clicked.connect(Form.on_click_bili_up_exclude) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.but_bili_up, self.but_bili_video)
        Form.setTabOrder(self.but_bili_video, self.but_bili_up_exc)
        Form.setTabOrder(self.but_bili_up_exc, self.but_lastpage)
        Form.setTabOrder(self.but_lastpage, self.but_nextpage)
        Form.setTabOrder(self.but_nextpage, self.scrollArea)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.but_bili_up.setText(_translate("Form", "bili_up"))
        self.but_bili_video.setText(_translate("Form", "bili_tag_v"))
        self.but_lastpage.setText(_translate("Form", "<"))
        self.but_nextpage.setText(_translate("Form", ">"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">TextLabel</span></p></body></html>"))
        self.but_bili_up_exc.setText(_translate("Form", "bili_up_exc"))
        self.toolButton_2.setText(_translate("Form", "..."))
        self.toolButton.setText(_translate("Form", "..."))
        self.toolButton_3.setText(_translate("Form", "..."))
