# Form implementation generated from reading ui file 'E:\VideoWatcher\UI\entryForm.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(386, 169)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 0, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 3, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 2, 1, 1)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.focus) # type: ignore
        self.pushButton_2.clicked.connect(Form.on_update_fillup) # type: ignore
        self.pushButton_4.clicked.connect(Form.on_update_allup) # type: ignore
        self.pushButton_5.clicked.connect(Form.on_update_allvideo) # type: ignore
        self.pushButton_3.clicked.connect(Form.on_update_fillvideo) # type: ignore
        self.pushButton_6.clicked.connect(Form.on_click_defaultplaylist) # type: ignore
        self.pushButton_8.clicked.connect(Form.on_click_dbview) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton, self.pushButton_6)
        Form.setTabOrder(self.pushButton_6, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.pushButton_5)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "focus"))
        self.pushButton_7.setToolTip(_translate("Form", "依照最近更新时间判断活跃度"))
        self.pushButton_7.setText(_translate("Form", "逾期up"))
        self.pushButton_2.setText(_translate("Form", "补全up"))
        self.pushButton_4.setText(_translate("Form", "所有up"))
        self.pushButton_6.setText(_translate("Form", "默认收藏夹"))
        self.pushButton_5.setText(_translate("Form", "所有video"))
        self.pushButton_3.setText(_translate("Form", "补全video"))
        self.pushButton_8.setText(_translate("Form", "dbview"))
