# Form implementation generated from reading ui file 'E:\VideoWatcher\UI\entryForm.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(449, 280)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.but_bili_2 = QtWidgets.QPushButton(parent=Form)
        self.but_bili_2.setObjectName("but_bili_2")
        self.gridLayout.addWidget(self.but_bili_2, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.but_dbview = QtWidgets.QPushButton(parent=Form)
        self.but_dbview.setObjectName("but_dbview")
        self.gridLayout.addWidget(self.but_dbview, 3, 0, 1, 1)
        self.but_bili_default_fold = QtWidgets.QPushButton(parent=Form)
        self.but_bili_default_fold.setObjectName("but_bili_default_fold")
        self.gridLayout.addWidget(self.but_bili_default_fold, 0, 1, 1, 1)
        self.but_focus = QtWidgets.QPushButton(parent=Form)
        self.but_focus.setObjectName("but_focus")
        self.gridLayout.addWidget(self.but_focus, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.but_bili_rebuild = QtWidgets.QPushButton(parent=Form)
        self.but_bili_rebuild.setObjectName("but_bili_rebuild")
        self.gridLayout.addWidget(self.but_bili_rebuild, 1, 2, 1, 1)
        self.but_bili_1 = QtWidgets.QPushButton(parent=Form)
        self.but_bili_1.setObjectName("but_bili_1")
        self.gridLayout.addWidget(self.but_bili_1, 1, 0, 1, 1)
        self.but_ytb_1 = QtWidgets.QPushButton(parent=Form)
        self.but_ytb_1.setObjectName("but_ytb_1")
        self.gridLayout.addWidget(self.but_ytb_1, 2, 0, 1, 1)
        self.but_ytb_2 = QtWidgets.QPushButton(parent=Form)
        self.but_ytb_2.setObjectName("but_ytb_2")
        self.gridLayout.addWidget(self.but_ytb_2, 2, 1, 1, 1)
        self.but_ytb_rebuild = QtWidgets.QPushButton(parent=Form)
        self.but_ytb_rebuild.setObjectName("but_ytb_rebuild")
        self.gridLayout.addWidget(self.but_ytb_rebuild, 2, 2, 1, 1)

        self.retranslateUi(Form)
        self.but_focus.clicked.connect(Form.focus) # type: ignore
        self.but_bili_default_fold.clicked.connect(Form.on_click_defaultplaylist) # type: ignore
        self.but_dbview.clicked.connect(Form.on_click_dbview) # type: ignore
        self.but_bili_1.clicked.connect(Form.on_update_fillup) # type: ignore
        self.but_bili_2.clicked.connect(Form.on_update_allup) # type: ignore
        self.but_bili_rebuild.clicked.connect(Form.on_click_bilibili_rebuild) # type: ignore
        self.but_ytb_1.clicked.connect(Form.on_click_ytb_fillup) # type: ignore
        self.but_ytb_2.clicked.connect(Form.on_click_ytb_allup) # type: ignore
        self.but_ytb_rebuild.clicked.connect(Form.on_click_ytb_rebuild) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.but_bili_2.setToolTip(_translate("Form", "更新B站所有的up主信息"))
        self.but_bili_2.setText(_translate("Form", "B站 up-2"))
        self.but_dbview.setText(_translate("Form", "dbview"))
        self.but_bili_default_fold.setToolTip(_translate("Form", "登录bilibili，前往默认收藏夹，获取前{默认}个视频"))
        self.but_bili_default_fold.setText(_translate("Form", "B站默认"))
        self.but_focus.setText(_translate("Form", "focus"))
        self.but_bili_rebuild.setToolTip(_translate("Form", "重建B站数据库"))
        self.but_bili_rebuild.setText(_translate("Form", "B站 rebuild"))
        self.but_bili_1.setToolTip(_translate("Form", "更新B站缺失的up主信息"))
        self.but_bili_1.setText(_translate("Form", "B站 up-1"))
        self.but_ytb_1.setToolTip(_translate("Form", "更新油管缺失的up主信息"))
        self.but_ytb_1.setText(_translate("Form", "Ytb up-1"))
        self.but_ytb_2.setToolTip(_translate("Form", "更新油管所有的up主信息"))
        self.but_ytb_2.setText(_translate("Form", "Ytb up-2"))
        self.but_ytb_rebuild.setToolTip(_translate("Form", "重建油管数据库"))
        self.but_ytb_rebuild.setText(_translate("Form", "Ytb rebuild"))
