# Form implementation generated from reading ui file 'E:\VideoWatcher\UI\infoFrom.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(258, 151)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.v_cover = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_cover.sizePolicy().hasHeightForWidth())
        self.v_cover.setSizePolicy(sizePolicy)
        self.v_cover.setMinimumSize(QtCore.QSize(80, 45))
        self.v_cover.setMaximumSize(QtCore.QSize(80, 45))
        self.v_cover.setStyleSheet("")
        self.v_cover.setText("")
        self.v_cover.setObjectName("v_cover")
        self.gridLayout_2.addWidget(self.v_cover, 0, 0, 1, 1)
        self.up_face = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up_face.sizePolicy().hasHeightForWidth())
        self.up_face.setSizePolicy(sizePolicy)
        self.up_face.setMinimumSize(QtCore.QSize(80, 80))
        self.up_face.setMaximumSize(QtCore.QSize(80, 80))
        self.up_face.setStyleSheet("")
        self.up_face.setText("")
        self.up_face.setObjectName("up_face")
        self.gridLayout_2.addWidget(self.up_face, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.but_govideo = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_govideo.sizePolicy().hasHeightForWidth())
        self.but_govideo.setSizePolicy(sizePolicy)
        self.but_govideo.setMinimumSize(QtCore.QSize(25, 25))
        self.but_govideo.setMaximumSize(QtCore.QSize(25, 16777215))
        self.but_govideo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.but_govideo.setText("")
        self.but_govideo.setDefault(False)
        self.but_govideo.setObjectName("but_govideo")
        self.gridLayout.addWidget(self.but_govideo, 0, 0, 1, 1)
        self.but_quit = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_quit.sizePolicy().hasHeightForWidth())
        self.but_quit.setSizePolicy(sizePolicy)
        self.but_quit.setMaximumSize(QtCore.QSize(24, 21))
        self.but_quit.setDefault(False)
        self.but_quit.setObjectName("but_quit")
        self.gridLayout.addWidget(self.but_quit, 0, 3, 1, 1)
        self.cb_add_v = QtWidgets.QComboBox(parent=Form)
        self.cb_add_v.setObjectName("cb_add_v")
        self.gridLayout.addWidget(self.cb_add_v, 1, 0, 1, 2)
        self.cb_del_v = QtWidgets.QComboBox(parent=Form)
        self.cb_del_v.setObjectName("cb_del_v")
        self.gridLayout.addWidget(self.cb_del_v, 1, 2, 1, 2)
        self.but_gospace = QtWidgets.QPushButton(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_gospace.sizePolicy().hasHeightForWidth())
        self.but_gospace.setSizePolicy(sizePolicy)
        self.but_gospace.setMinimumSize(QtCore.QSize(25, 25))
        self.but_gospace.setMaximumSize(QtCore.QSize(25, 16777215))
        self.but_gospace.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.but_gospace.setText("")
        self.but_gospace.setDefault(False)
        self.but_gospace.setObjectName("but_gospace")
        self.gridLayout.addWidget(self.but_gospace, 2, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(parent=Form)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 2, 3, 1, 1)
        self.cb_add_up = QtWidgets.QComboBox(parent=Form)
        self.cb_add_up.setObjectName("cb_add_up")
        self.gridLayout.addWidget(self.cb_add_up, 3, 0, 1, 2)
        self.cb_del_up = QtWidgets.QComboBox(parent=Form)
        self.cb_del_up.setObjectName("cb_del_up")
        self.gridLayout.addWidget(self.cb_del_up, 3, 2, 1, 2)
        self.label_title = QtWidgets.QLabel(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 1, 1, 2)
        self.cb_upselect = QtWidgets.QCheckBox(parent=Form)
        self.cb_upselect.setStyleSheet("QCheckBox::indicator:unchecked {\n"
"    border: 2px solid #999;\n"
"    border-radius: 4px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    border: 2px solid red;\n"
"    border-radius: 4px;\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    border: 2px solid green;\n"
"    border-radius: 4px;\n"
"    background-color: green;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    text-align: center;\n"
"}")
        self.cb_upselect.setTristate(True)
        self.cb_upselect.setObjectName("cb_upselect")
        self.gridLayout.addWidget(self.cb_upselect, 2, 1, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.but_govideo.clicked.connect(Form.slot_goto_video) # type: ignore
        self.but_gospace.clicked.connect(Form.slot_goto_space) # type: ignore
        self.cb_add_v.activated['int'].connect(Form.on_video_add) # type: ignore
        self.cb_del_v.activated['int'].connect(Form.on_video_del) # type: ignore
        self.cb_add_up.activated['int'].connect(Form.on_up_add) # type: ignore
        self.cb_del_up.activated['int'].connect(Form.on_up_del) # type: ignore
        self.toolButton.clicked.connect(Form.on_click_toolbut) # type: ignore
        self.but_quit.clicked.connect(Form.del_infoW) # type: ignore
        self.cb_upselect.checkStateChanged['Qt::CheckState'].connect(Form.on_up_tristate) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.but_govideo, self.but_quit)
        Form.setTabOrder(self.but_quit, self.cb_add_v)
        Form.setTabOrder(self.cb_add_v, self.cb_del_v)
        Form.setTabOrder(self.cb_del_v, self.but_gospace)
        Form.setTabOrder(self.but_gospace, self.cb_upselect)
        Form.setTabOrder(self.cb_upselect, self.toolButton)
        Form.setTabOrder(self.toolButton, self.cb_add_up)
        Form.setTabOrder(self.cb_add_up, self.cb_del_up)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.but_quit.setText(_translate("Form", "X"))
        self.toolButton.setText(_translate("Form", "..."))
        self.label_title.setText(_translate("Form", "title"))
        self.cb_upselect.setText(_translate("Form", "up_name"))
